### ISSUE TITLE
前置摄像头拍摄崩溃Android7.1

### ISSUE THREAD

**Issue by abc20899** [CJT2325/CameraView#101]
java.lang.RuntimeException: setParameters failed
                                                                            at android.hardware.Camera.native_setParameters(Native Method)
                                                                            at android.hardware.Camera.setParameters(Camera.java:1968)
                                                                            at com.hkby.footapp.widget.cameraview.CameraInterface.doAutoFocus(CameraInterface.java:792)
                                                                            at com.hkby.footapp.widget.cameraview.CameraInterface.access$600(CameraInterface.java:48)
                                                                            at com.hkby.footapp.widget.cameraview.CameraInterface$3.onAutoFocus(CameraInterface.java:522)
                                                                            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1146)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)

**Comment by CJT2325** [comment]
这个doAutoFocus我的库里面没有把？
