### ISSUE TITLE
the surface has been released

### ISSUE THREAD

**Issue by leohan1992** [CJT2325/CameraView#103]
复现步骤，长按录制视频过程中，点一下返回，再打开view，长按录制，即发生崩溃
```
java.lang.IllegalArgumentException:The surface has been released 
at android.media.MediaPlayer._setVideoSurface(Native Method)
at android.media.MediaPlay.setSurface(MediaPlayer.java756)
at com.cjt2325.cameralibrary.JCameraView$7.run(JCameraView.java:454)
at java.lang.Thread.run(Thread.jaava:760)
```
求解

**Comment by shuigesuntao** [comment]
同样有这个问题

**Comment by leohan1992** [comment]
为什么没有解答。。。。
