### ISSUE TITLE
切换闪光灯模式时崩溃

### ISSUE THREAD

**Issue by JasonZhu19910601** [CJT2325/CameraView#124]
型号：华为 揽阅M3 BTV-DL09 平板
出现异常的操作：点击界面右上角的切换闪光灯模式按钮，从自动切换到打开模式时报错。
异常日志：AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.leading.jinan, PID: 8637
                                                                 java.lang.RuntimeException: setParameters failed
                                                                     at android.hardware.Camera.native_setParameters(Native Method)
                                                                     at android.hardware.Camera.setParameters(Camera.java:2586)
                                                                     at com.cjt2325.cameralibrary.CameraInterface.setFlashMode(CameraInterface.java:274)
                                                                     at com.cjt2325.cameralibrary.state.PreviewState.flash(PreviewState.java:107)
                                                                     at com.cjt2325.cameralibrary.state.CameraMachine.flash(CameraMachine.java:127)
                                                                     at com.cjt2325.cameralibrary.JCameraView.setFlashRes(JCameraView.java:591)
                                                                     at com.cjt2325.cameralibrary.JCameraView.access$100(JCameraView.java:47)
                                                                     at com.cjt2325.cameralibrary.JCameraView$1.onClick(JCameraView.java:166)
                                                                     at android.view.View.performClick(View.java:5646)
                                                                     at android.view.View$PerformClick.run(View.java:22459)
                                                                     at android.os.Handler.handleCallback(Handler.java:761)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                     at android.os.Looper.loop(Looper.java:156)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by zstartw** [comment]
CameraInterface.java要添加下面判断

```
public void setFlashMode(String flashMode) {
        if (mCamera == null)
            return;
        Camera.Parameters params = mCamera.getParameters();

        //解决如果没有闪光灯的时候 调用相关api的时候会报错的问题
        if (params.getSupportedFlashModes() != null && params.getSupportedFlashModes().contains(flashMode)){
            params.setFlashMode(flashMode);
            mCamera.setParameters(params);
        }
    }
```
