### ISSUE TITLE
使用源码将camera导入项目，与现有版本不一致会直接导致crash

### ISSUE THREAD

**Issue by JackyChen1996** [CJT2325/CameraView#148]
Binary XML file line #0<vector> tag requires viewportWidth > 0

**Comment by JackyChen1996** [comment]
01-12 11:43:32.036 23998-23998/com.example.jacky.totoland E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.jacky.totoland, PID: 23998
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.jacky.totoland/view.TakePhotoActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.cjt2325.cameralibrary.JCameraView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2796)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.cjt2325.cameralibrary.JCameraView
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.cjt2325.cameralibrary.JCameraView
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:656)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                at view.TakePhotoActivity.onCreate(TakePhotoActivity.java:27)
                                                                                at android.app.Activity.performCreate(Activity.java:6910)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                             Caused by: android.content.res.Resources$NotFoundException: Drawable com.example.jacky.totoland:drawable/ic_camera_enhance_black_24dp with resource ID #0x7f0800a3
                                                                             Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_camera_enhance_black_24dp.xml from drawable resource ID #0x7f0800a3
                                                                                at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:935)
                                                                                at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:834)
                                                                                at android.content.Context.getDrawable(Context.java:529)
                                                                                at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:351)
                                                                                at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:200)
                                                                                at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                                at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
01-12 11:43:32.036 23998-23998/com.example.jacky.totoland E/AndroidRuntime:     at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
                                                                                at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
                                                                                at com.cjt2325.cameralibrary.JCameraView.initView(JCameraView.java:157)
                                                                                at com.cjt2325.cameralibrary.JCameraView.<init>(JCameraView.java:140)
                                                                                at com.cjt2325.cameralibrary.JCameraView.<init>(JCameraView.java:122)
                                                                                at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:656)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                at view.TakePhotoActivity.onCreate(TakePhotoActivity.java:27)
                                                                                at android.app.Activity.performCreate(Activity.java:6910)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2749)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1570)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                at android.os.Looper.loop(Looper.java:156)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                             Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0<vector> tag requires viewportWidth > 0
                                                                                at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:637)
                                                                                at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:595)
                                                                                at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:133)
                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1224)
                                                                                at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1197)
                                                                                at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:925)
                                                                                	... 37 more

**Comment by JackyChen1996** [comment]
将 xml中 app:iconSrc="@drawable/ic_camera_enhance_black_24dp"/删掉即可，不是版本不一致的问题，而是xml中的问题 。。。没注意分析log
