### ISSUE TITLE
华为荣耀7系统版本EMUI4.0.3在打开摄像头页面报错

### ISSUE THREAD

**Issue by soya4338443** [CJT2325/CameraView#194]
java.lang.RuntimeException: Unknown camera ID
	at android.hardware.Camera._getCameraInfo(Native Method)
	at android.hardware.Camera.getCameraInfo(Camera.java:278)
	at com.cjt2325.cameralibrary.util.CameraParamUtil.getCameraDisplayOrientation(CameraParamUtil.java:130)
	at com.cjt2325.cameralibrary.CameraInterface.setSwitchView(CameraInterface.java:118)
	at com.cjt2325.cameralibrary.JCameraView.onResume(JCameraView.java:289)
	at com.renpeng.zyj.ui.activity.CameraActivity.onResume(CameraActivity.java:121)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1266)
	at android.app.Activity.performResume(Activity.java:6446)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3129)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3170)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
	at android.app.ActivityThread.access$900(ActivityThread.java:165)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5621)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by linghp** [comment]
我也遇到了，楼主解决了吗
