### ISSUE TITLE
在视频拍摄模式下，有时候轻点也会触发拍摄，后点击返回会崩溃

### ISSUE THREAD

**Issue by hongbobo614** [CJT2325/CameraView#195]
07-18 10:57:28.520 12619-12619/com.g2cc.manager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.g2cc.manager, PID: 12619
    java.lang.RuntimeException: startPreview failed
        at android.hardware.Camera.startPreview(Native Method)
        at com.cjt2325.cameralibrary.CameraInterface.doStartPreview(CameraInterface.java:396)
        at com.cjt2325.cameralibrary.state.BorrowVideoState.start(BorrowVideoState.java:28)
        at com.cjt2325.cameralibrary.state.CameraMachine.start(CameraMachine.java:71)
        at com.cjt2325.cameralibrary.JCameraView.resetState(JCameraView.java:428)
        at com.cjt2325.cameralibrary.state.BorrowVideoState.cancle(BorrowVideoState.java:70)
        at com.cjt2325.cameralibrary.state.CameraMachine.cancle(CameraMachine.java:111)
        at com.cjt2325.cameralibrary.JCameraView$4.cancel(JCameraView.java:232)
        at com.cjt2325.cameralibrary.CaptureLayout$3.onClick(CaptureLayout.java:205)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)

**Comment by pumatus** [comment]
解决方案是什么
