### ISSUE TITLE
报错,两个界面一个拍照一个拍视频,会报错

### ISSUE THREAD

**Issue by kevin321happy** [CJT2325/CameraView#199]
java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                        at android.hardware.Camera.native_getParameters(Native Method)
                                                                        at android.hardware.Camera.getParameters(Camera.java:2365)
                                                                        at com.cjt2325.cameralibrary.CameraInterface.doStartPreview(CameraInterface.java:371)
                                                                        at com.cjt2325.cameralibrary.KCameraView.cameraHasOpened(KCameraView.java:247)
                                                                        at com.cjt2325.cameralibrary.CameraInterface.doOpenCamera(CameraInterface.java:304)
                                                                        at com.cjt2325.cameralibrary.KCameraView$5.run(KCameraView.java:275)

**Comment by kevin321happy** [comment]
使用两个JCameraView对象时会报错

**Comment by ydajiang** [comment]
还有这种操作？？？

**Comment by aojiaoqiang** [comment]
你这个操作太骚了吧，一个相机硬件只能同时有一个程序调用，另一个程序会被抛异常，你可以一个前置一个后置
