### ISSUE TITLE
第一次使用权限允许后，一直处理黑屏状态呢？没有预览出现， 重新再进一次又可以了..  怎么解决？

### ISSUE THREAD

**Issue by chenjunyubt** [CJT2325/CameraView#209]
java.lang.RuntimeException: Fail to connect to camera service
11-11 07:34:01.658 10327-10341/com.cjt2325.cameraview W/System.err:     at android.hardware.Camera.<init>(Camera.java:495)
11-11 07:34:01.658 10327-10341/com.cjt2325.cameraview W/System.err:     at android.hardware.Camera.open(Camera.java:341)
11-11 07:34:01.658 10327-10341/com.cjt2325.cameraview W/System.err:     at com.cjt2325.cameralibrary.CameraInterface.openCamera(CameraInterface.java:313)
11-11 07:34:01.658 10327-10341/com.cjt2325.cameraview W/System.err:     at com.cjt2325.cameralibrary.CameraInterface.doOpenCamera(CameraInterface.java:300)
11-11 07:34:01.658 10327-10341/com.cjt2325.cameraview W/System.err:     at com.cjt2325.cameralibrary.JCameraView$7.run(JCameraView.java:308)

**Comment by chenjunyubt** [comment]
问题解决了：  解决6.0以上系统 获取权限出现黑屏的问题
建议在 jCameraListener中增加 onRequestPermissions方法，获取权限后，再打开相机
public interface JCameraListener {

    void captureSuccess(Bitmap bitmap);

    void recordSuccess(String url, Bitmap firstFrame);

    void onRequestPermissions();
}


在获取到相机权限后，再去调用找开相册的操作，即可解决黑屏问题
 //SurfaceView生命周期
    @Override
    public void surfaceCreated(SurfaceHolder holder) {
        LogUtil.e("JCameraView SurfaceCreated");
        jCameraLisenter.onRequestPermissions();
    }

    public void onOpenCamera(){
        try{
            new Thread() {
                @Override
                public void run() {
                    CameraInterface.getInstance().doOpenCamera(JCameraView.this);
                }
            }.start();
        }catch (Exception e){
            e.printStackTrace();
        }
    }
