### ISSUE TITLE
撤销第一次录制的视频，第二次录制时crash

### ISSUE THREAD

**Issue by wl0073921** [CJT2325/CameraView#249]
Pixel 3a，Android 10

Process: com.zxing.cameraapplication, PID: 3383
    java.lang.IllegalStateException
        at android.media.MediaPlayer._prepare(Native Method)
        at android.media.MediaPlayer.prepare(MediaPlayer.java:1274)
        at com.cjt2325.cameralibrary.JCameraView$9.run(JCameraView.java:517)
        at java.lang.Thread.run(Thread.java:919)

**Comment by wl0073921** [comment]
我已经修复了这个问题，原因在于视频的拍摄和播放用的是一个Surface，稍微不注意，两者之间就会产生干扰，所以我改为了拍摄一个VideoView，播放是一个VideoView，在播放的开始和结束的时候，控制VideoView的可见性。同时，可见性切换会黑一下，使用一个淡出动画过渡。
