### ISSUE TITLE
TextureView doesn't support displaying a background drawable

### ISSUE THREAD

**Issue by gwokwong** [CJT2325/CameraView#25]
用25的sdk编译会出现这样的问题。
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.takePicture(android.hardware.Camera$ShutterCallback, android.hardware.Camera$PictureCallback, android.hardware.Camera$PictureCallback)' on a null object reference
                                                                         at com.camera.CameraInterface.takePicture(CameraInterface.java:220)
                                                                         at com..camera.JCameraView$2.takePictures(JCameraView.java:220)
                                                                         at com.camera.CaptureLayout$2.takePictures(CaptureLayout.java:149)
                                                                         at com.camera.CaptureButton.handlerUnpressByState(CaptureButton.java:162)
                                                                         at com.camera.CaptureButton.onTouchEvent(CaptureButton.java:148)

**Comment by CJT2325** [comment]
@guowang1102 你试试最新的1.0.4，我把TextureView改为VideoView了
