### ISSUE TITLE
还没有开始录像的时候，点点屏幕或者开始录制按钮那里，就崩溃了

### ISSUE THREAD

**Issue by WarriorYu** [CJT2325/CameraView#255]
还没有开始录像的时候，点点屏幕或者开始录制按钮那里，就崩溃了。希望作者维护一下这个库，这个库的功能很贴近实际开发的需求，谢谢作者。

2019-11-13 15:05:18.998 17896-17896/com.simple.app E/PressGestureDetector: Time out for start text boom, interval=1472
2019-11-13 15:05:30.326 17896-17896/com.simple.app E/AudioRecord: start() status -38
2019-11-13 15:05:30.327 17896-17896/com.simple.app E/JCameraView: AudioPermissionError
2019-11-13 15:05:30.830 17896-17896/com.simple.app E/PressGestureDetector: Time out for start text boom, interval=1013
2019-11-13 15:05:34.567 17896-18338/com.simple.app E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
2019-11-13 15:05:34.567 17896-18338/com.simple.app E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
2019-11-13 15:05:34.567 17896-18338/com.simple.app E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
2019-11-13 15:05:34.567 17896-18338/com.simple.app E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
2019-11-13 15:05:34.685 17896-18338/com.simple.app E/AndroidRuntime: FATAL EXCEPTION: Thread-53
    Process: com.simple.app, PID: 17896
    java.lang.IllegalArgumentException: The surface has been released
        at android.media.MediaPlayer._setVideoSurface(Native Method)
        at android.media.MediaPlayer.setSurface(MediaPlayer.java:752)
        at com.cjt2325.cameralibrary.JCameraView$9.run(JCameraView.java:498)
        at java.lang.Thread.run(Thread.java:761)

**Comment by xionger0520** [comment]
@WarriorYu 我基于这个库重写了   修复了动画交互和相机操作的一些bug
