### ISSUE TITLE
在 7.0 系统上会崩溃

### ISSUE THREAD

**Issue by coolyunyun** [CJT2325/CameraView#45]
在 7.0 系统上会崩溃  不妨测试下。

**Comment by CJT2325** [comment]
是权限问题吗

**Comment by CJT2325** [comment]
你报一下你的设备

**Comment by coolyunyun** [comment]
我下载那个demo apk 也是报错啊   你里面没加权限判断吗？  类库里
设备  华为的7.0设备

**Comment by CJT2325** [comment]
嗯，判断了，你贴一下log看看报错原因，我这边7.0机子能运行

**Comment by coolyunyun** [comment]
FATAL EXCEPTION: main
                                                              Process: com.tuoying.zy, PID: 4075
                                                              java.lang.RuntimeException: takePicture failed, error=-38
                                                                  at android.hardware.Camera.native_takePicture(Native Method)
                                                                  at android.hardware.Camera.takePicture(Camera.java:1772)
                                                                  at android.hardware.Camera.takePicture(Camera.java:1705)
                                                                  at com.cjt2325.cameralibrary.CameraInterface.takePicture(CameraInterface.java:366)
                                                                  at com.cjt2325.cameralibrary.JCameraView$2.takePictures(JCameraView.java:202)
                                                                  at com.cjt2325.cameralibrary.CaptureLayout$2.takePictures(CaptureLayout.java:160)
                                                                  at com.cjt2325.cameralibrary.CaptureButton.handlerUnpressByState(CaptureButton.java:194)
                                                                  at com.cjt2325.cameralibrary.CaptureButton.onTouchEvent(CaptureButton.java:178)
                                                                  at android.view.View.dispatchTouchEvent(View.java:10012)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
                                                                  at android.view.View.dispatchPointerEvent(View.java:10232)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4856)
                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4717)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4395)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4452)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4302)
                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4268)
                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4276)
                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4249)
                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6676)
                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6650)
                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6611)
                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6803)
                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
                                                                  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                  at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
05-31 14:07:52.324 4075-4075/com.tuoying.zy E/AndroidRuntime:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6750)
                                                                  at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6831)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:661)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
                                                                  at android.os.Handler.handleCallback(Handler.java:761)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                  at android.os.Looper.loop(Looper.java:156)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by CJT2325** [comment]
加QQ 445263848

**Comment by jiugege** [comment]
我也出现了这个问题，手机是乐视6.0系统，请问下这个问题修复了吗，求教大神
