### ISSUE TITLE
开始录像崩溃

### ISSUE THREAD

**Issue by upperLucky** [CJT2325/CameraView#54]
测试机努比亚 4.4.2
开始长按录像就崩溃,报错log如下,求解

AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ruanke.niannian, PID: 5344
                                                                   java.lang.RuntimeException: stop failed.
                                                                       at android.media.MediaRecorder.stop(Native Method)
                                                                       at com.cjt2325.cameralibrary.CameraInterface.stopRecord(CameraInterface.java:457)
                                                                       at com.cjt2325.cameralibrary.JCameraView$2.recordEnd(JCameraView.java:258)
                                                                       at com.cjt2325.cameralibrary.CaptureLayout$2.recordEnd(CaptureLayout.java:177)
                                                                       at com.cjt2325.cameralibrary.CaptureButton.recordEnd(CaptureButton.java:260)
                                                                       at com.cjt2325.cameralibrary.CaptureButton.access$1000(CaptureButton.java:25)
                                                                       at com.cjt2325.cameralibrary.CaptureButton$RecordRunnable$2.onAnimationEnd(CaptureButton.java:238)
                                                                       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
                                                                       at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
                                                                       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
                                                                       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:543)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5137)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:617)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by CJT2325** [comment]
@upperLucky 445263848
