### ISSUE TITLE
初次打开报这个错enable shutter sound failed，第二次以后便不会

### ISSUE THREAD

**Issue by yovenny** [CJT2325/CameraView#59]
```
d[Thread-899,5,main]
                                                                 UncaughtException detected: java.lang.RuntimeException: enable shutter sound failed
                                                                     at android.hardware.Camera._enableShutterSound(Native Method)
                                                                     at android.hardware.Camera.enableShutterSound(Camera.java:2052)
                                                                     at com.cjt2325.cameralibrary.CameraInterface.openCamera(CameraInterface.java:280)
                                                                     at com.cjt2325.cameralibrary.CameraInterface.doOpenCamera(CameraInterface.java:265)
                                                                     at com.cjt2325.cameralibrary.JCameraView$5.run(JCameraView.java:422)
06-12 09:50:38.912 25773-29244/com.yovenny.yuyue E/AndroidRuntime: FATAL EXCEPTION: Thread-899
                                                                   Process: com.yovenny.yuyue, PID: 25773
                                                                   java.lang.RuntimeException: enable shutter sound failed
                                                                       at android.hardware.Camera._enableShutterSound(Native Method)
                                                                       at android.hardware.Camera.enableShutterSound(Camera.java:2052)
                                                                       at com.cjt2325.cameralibrary.CameraInterface.openCamera(CameraInterface.java:280)
                                                                       at com.cjt2325.cameralibrary.CameraInterface.doOpenCamera(CameraInterface.java:265)
                                                                       at com.cjt2325.cameralibrary.JCameraView$5.run(JCameraView.java:422)
```

**Comment by CJT2325** [comment]
嗯，我之前已经修复了这个问题，代码更新了，但是Demo还么更新，我刚刚上传了最新的Demo了，你重新下载试试看

**Comment by CJT2325** [comment]
JCenter版本可以也有点Bug，等修复完BUG之后，再更新一个版本 @yovenny

**Comment by yovenny** [comment]
我是昨天拉下来加入module的，我现在再试试哈，谢谢呀

**Comment by CJT2325** [comment]
我重新添加了捕获异常，现在应该不会崩溃了

**Comment by yovenny** [comment]
那边捕获？，没看到相关代码的，这个是什么原因丫

**Comment by yovenny** [comment]
哦哦，看到了。。
