### ISSUE TITLE
在vivo x6plusD手机上录像和拍照出错率非常高

### ISSUE THREAD

**Issue by taiwandao** [CJT2325/CameraView#62]
java.lang.RuntimeException: Camera is being used after Camera.release() was called
	at android.hardware.Camera._stopPreview(Native Method)
	at android.hardware.Camera.stopPreview(Camera.java:870)
	at com.cjt2325.cameralibrary.CameraInterface.doStartPreview(CameraInterface.java:343)
	at com.cjt2325.cameralibrary.JCameraView.cameraHasOpened(JCameraView.java:403)
	at com.cjt2325.cameralibrary.CameraInterface.doOpenCamera(CameraInterface.java:267)
	at com.cjt2325.cameralibrary.JCameraView$7.run(JCameraView.java:628)
 
java.lang.RuntimeException: takePicture failed
	at android.hardware.Camera.native_takePicture(Native Method)
	at android.hardware.Camera.takePicture(Camera.java:1601)
	at android.hardware.Camera.takePicture(Camera.java:1545)
	at com.cjt2325.cameralibrary.CameraInterface.takePicture(CameraInterface.java:394)
	at com.cjt2325.cameralibrary.JCameraView$2.takePictures(JCameraView.java:223)
	at com.cjt2325.cameralibrary.CaptureLayout$2.takePictures(CaptureLayout.java:161)
	at com.cjt2325.cameralibrary.CaptureButton.handlerUnpressByState(CaptureButton.java:212)
	at com.cjt2325.cameralibrary.CaptureButton.onTouchEvent(CaptureButton.java:195)
	at android.view.View.dispatchTouchEvent(View.java:8505)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2123)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2487)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1785)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2835)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2446)
	at android.view.View.dispatchPointerEvent(View.java:8712)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4239)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3621)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3687)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3647)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3776)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3655)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3833)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3621)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3687)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3647)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3655)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3621)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5965)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5939)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5899)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by taiwandao** [comment]
以上内容是两个异常
